## Model Evaluation

In [2]:
import os
os.chdir('..')
%pwd

'/root/autodl-tmp/counterfactual_fairness_emotional_recognition'

In [3]:
import pickle
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from train import test
from datasets import IEMOCAPEval

### Setting up test dataset

In [4]:
test_dataset = IEMOCAPEval(partition='test')
test_loader = DataLoader(test_dataset, batch_size=128, shuffle=False, num_workers=1, pin_memory=True)

In [5]:
CHECKPOINT_MODEL_DIR1 = "checkpoint/20220429_114253/model_locked_dropout_activation_reg_twin.pth"
model1 = torch.load(CHECKPOINT_MODEL_DIR1).cuda()

CHECKPOINT_MODEL_DIR2 = "checkpoint/20220429_135037/model_locked_dropout_activation_reg_vanilla.pth"
model2 = torch.load(CHECKPOINT_MODEL_DIR2).cuda()
criterion = nn.CrossEntropyLoss()

### Evaluate model on test set

In [6]:
test(model1, test_loader, test_dataset, criterion)

*****************************************************************
Evaluation on Test Set:
Test cost: 1.37
Test accuracy: 0.371
Test UAR: 0.4618
Test Confusion Matrix:["ang","sad","hap","neu"]
[[19  2  4  4]
 [ 7 63 16 24]
 [21  8 28 14]
 [24 64 81 49]]
Fairness Scores (in terms of equal opportunities):
["ang","sad","hap","neu"]
[0.625      0.80660377 0.96153846 0.87689594]
*****************************************************************


In [7]:
test(model2, test_loader, test_dataset, criterion)

*****************************************************************
Evaluation on Test Set:
Test cost: 1.34
Test accuracy: 0.388
Test UAR: 0.4693
Test Confusion Matrix:["ang","sad","hap","neu"]
[[23  1  2  3]
 [16 55 13 26]
 [26  8 19 18]
 [42 76 31 69]]
Fairness Scores (in terms of equal opportunities):
["ang","sad","hap","neu"]
[0.82417582 0.71698113 0.32451923 0.85176991]
*****************************************************************
