## Model Evaluation

In [1]:
import os
os.chdir('..')
%pwd

'/root/autodl-tmp/counterfactual_fairness_emotional_recognition'

In [2]:
import pickle
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from train import test
from datasets import IEMOCAPEval

### Setting up test dataset

In [3]:
test_dataset = IEMOCAPEval(partition='test')
test_loader = DataLoader(test_dataset, batch_size=128, shuffle=False, num_workers=1, pin_memory=True)

CHECKPOINT_MODEL_DIR = "checkpoint/20220424_100531/model_acrnn_locked_dropout_act_reg0.3_0.5406.pth"
model = torch.load(CHECKPOINT_MODEL_DIR).cuda()
criterion = nn.CrossEntropyLoss()

### Evaluate model on test set

In [4]:
test(model, test_loader, test_dataset, criterion)

*****************************************************************
Evaluation on Test Set:
Test cost: 1.3
Test accuracy: 0.435
Test UAR: 0.5062
Test Confusion Matrix:["ang","sad","hap","neu"]
[[25  2  1  1]
 [ 9 71 14 16]
 [29 12 11 19]
 [35 69 35 79]]
Fairness Scores (in terms of equal opportunities):
["ang","sad","hap","neu"]
[0.84183673 0.83349057 0.69333333 0.95302927]
*****************************************************************
