## Model Evaluation

In [ ]:
import os
os.chdir('..')

/content


In [ ]:
%cd /content

/content


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Copy Dataset

In [ ]:
!cp /content/drive/MyDrive/11785/project/rawdata /content/ -r

# Training

In [ ]:
%cd /content/drive/MyDrive/11785/project

/content/drive/MyDrive/11785/project


In [ ]:
!pip install pytorch-nlp
!pip install python_speech_features

     |████████████████████████████████| 90 kB 6.7 MB/s 
  Created wheel for python-speech-features: filename=python_speech_features-0.6-py3-none-any.whl size=5888 sha256=3fba7d218e3b4d35b31a041501d1150f5979fa4a87f1a0308f17d340f125d169
  Stored in directory: /root/.cache/pip/wheels/b0/0e/94/28cd6afa3cd5998a63eef99fe31777acd7d758f59cf24839eb
Successfully built python-speech-features


In [ ]:
!python /content/drive/MyDrive/11785/project/train.py

/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1320: UserWarning: dropout2d: Received a 2-D input to dropout2d, which is deprecated and will result in an error in a future release. To retain the behavior and silence this warning, please use dropout instead. Note that dropout2d exists to provide channel-wise dropout on inputs with 2 spatial dimensions, a channel dimension, and an optional batch dimension (i.e. 3D or 4D inputs).
  warnings.warn(warn_msg)
*****************************************************************
Evaluation on Test Set:
Test cost: 1.23
Test accuracy: 0.5
Test UAR: 0.5515
Test Confusion Matrix:["ang","sad","hap","neu"]
[[22  1  4  2]
 [ 7 71 10 22]
 [17  5 26 23]
 [35 42 46 95]]
Fairness Scores (in terms of equal opportunities):
["ang","sad","hap","neu"]
[0.6122449  0.65994854 0.63765182 0.90984513]
*****************************************************************


In [ ]:
label = np.load("/content/drive/MyDrive/11785/project/rawdata/IEMOCAP_test_label_converted.npy", allow_pickle=True).reshape(-1)
for i in range(len(label)):
  if label[i] > 3:
    label[i] = 3
print(label)
f = open("/content/drive/MyDrive/11785/project/rawdata/IEMOCAP_test_label_converted.npy",'wb')
np.save(f, label)
f.close()

[1 3 1 3 3 1 0 3 3 0 2 3 2 2 3 2 3 3 3 1 3 0 1 1 1 2 1 3 3 3 1 0 1 3 3 1 3
 1 2 1 2 2 3 1 1 3 2 1 3 3 3 2 3 3 2 1 1 3 2 2 2 3 3 3 3 3 2 1 3 1 2 1 2 2
 3 3 1 1 1 2 3 3 1 3 0 3 3 3 3 2 3 2 1 3 3 2 1 3 0 3 3 3 3 1 3 2 2 3 2 3 1
 1 0 3 0 0 1 3 3 1 1 3 1 3 2 1 1 3 3 0 0 3 1 3 3 1 3 2 3 2 0 1 3 3 3 3 2 1
 3 3 3 3 3 1 3 2 1 3 3 1 3 3 3 2 3 3 1 3 3 1 3 3 3 1 3 1 1 3 3 3 3 2 1 3 2
 2 3 1 1 1 3 3 1 3 3 2 3 1 1 3 2 3 3 2 2 3 1 1 1 3 3 3 1 2 3 3 3 3 1 1 1 3
 3 3 3 1 3 3 2 3 1 2 2 3 0 1 2 2 1 3 3 3 3 3 1 2 2 3 1 3 2 1 3 1 1 2 3 1 2
 3 1 3 1 3 0 1 3 3 3 1 3 3 2 3 3 3 1 3 2 1 3 3 1 2 2 0 3 3 3 3 2 2 3 2 3 3
 3 3 3 3 2 0 1 3 2 2 1 3 3 2 3 3 3 3 2 1 3 1 2 3 3 3 3 2 3 3 1 3 3 3 3 1 2
 3 3 0 3 3 2 3 2 3 3 0 0 1 1 3 0 3 1 2 1 3 3 1 0 3 3 1 3 3 1 1 1 1 0 1 1 1
 3 2 2 1 1 3 0 1 3 2 2 1 3 3 3 3 3 0 1 0 1 0 3 1 3 1 2 1 3 1 3 1 3 1 3 3 2
 1 3 1 3 2 3 2 3 1 1 3 3 2 3 3 3 2 0 1 1 3]


In [ ]:
label = np.load("/content/rawdata/IEMOCAP_test_label_converted.npy", allow_pickle=True).reshape(-1)
print(label)

[1 3 1 3 3 1 0 3 3 0 2 3 2 2 3 2 3 3 3 1 3 0 1 1 1 2 1 3 3 3 1 0 1 3 3 1 3
 1 2 1 2 2 3 1 1 3 2 1 3 3 3 2 3 3 2 1 1 3 2 2 2 3 3 3 3 3 2 1 3 1 2 1 2 2
 3 3 1 1 1 2 3 3 1 3 0 3 3 3 3 2 3 2 1 3 3 2 1 3 0 3 3 3 3 1 3 2 2 3 2 3 1
 1 0 3 0 0 1 3 3 1 1 3 1 3 2 1 1 3 3 0 0 3 1 3 3 1 3 2 3 2 0 1 3 3 3 3 2 1
 3 3 3 3 3 1 3 2 1 3 3 1 3 3 3 2 3 3 1 3 3 1 3 3 3 1 3 1 1 3 3 3 3 2 1 3 2
 2 3 1 1 1 3 3 1 3 3 2 3 1 1 3 2 3 3 2 2 3 1 1 1 3 3 3 1 2 3 3 3 3 1 1 1 3
 3 3 3 1 3 3 2 3 1 2 2 3 0 1 2 2 1 3 3 3 3 3 1 2 2 3 1 3 2 1 3 1 1 2 3 1 2
 3 1 3 1 3 0 1 3 3 3 1 3 3 2 3 3 3 1 3 2 1 3 3 1 2 2 0 3 3 3 3 2 2 3 2 3 3
 3 3 3 3 2 0 1 3 2 2 1 3 3 2 3 3 3 3 2 1 3 1 2 3 3 3 3 2 3 3 1 3 3 3 3 1 2
 3 3 0 3 3 2 3 2 3 3 0 0 1 1 3 0 3 1 2 1 3 3 1 0 3 3 1 3 3 1 1 1 1 0 1 1 1
 3 2 2 1 1 3 0 1 3 2 2 1 3 3 3 3 3 0 1 0 1 0 3 1 3 1 2 1 3 1 3 1 3 1 3 3 2
 1 3 1 3 2 3 2 3 1 1 3 3 2 3 3 3 2 0 1 1 3]


In [ ]:
import pickle
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from train import test
from datasets import IEMOCAPEval

### Setting up test dataset

In [ ]:
test_dataset = IEMOCAPEval(partition='test')
test_loader = DataLoader(test_dataset, batch_size=128, shuffle=False, num_workers=1, pin_memory=True)

CHECKPOINT_MODEL_DIR = "checkpoint/20220424_100531/model_acrnn_locked_dropout_act_reg0.3_0.5406.pth"
model = torch.load(CHECKPOINT_MODEL_DIR).cuda()
criterion = nn.CrossEntropyLoss()

### Evaluate model on test set

In [ ]:
test(model, test_loader, test_dataset, criterion)

*****************************************************************
Evaluation on Test Set:
Test cost: 1.3
Test accuracy: 0.435
Test UAR: 0.5062
Test Confusion Matrix:["ang","sad","hap","neu"]
[[25  2  1  1]
 [ 9 71 14 16]
 [29 12 11 19]
 [35 69 35 79]]
Fairness Scores (in terms of equal opportunities):
["ang","sad","hap","neu"]
[0.84183673 0.83349057 0.69333333 0.95302927]
*****************************************************************


In [ ]:
import pickle as pkl
import pandas as pd
with open("/content/drive/MyDrive/11785/project/log/log_20220428_030303_acrnn_conterfactural_.pkl", "rb") as f:
    f = pkl.load(f)
print(f) 
   
# df = pd.DataFrame(f)
# df.to_csv(r'/content/drive/MyDrive/11785/project/log/log_20220428_030303_acrnn_conterfactural.csv')