## Set up

In [1]:
! pip install pytorch-nlp

     |████████████████████████████████| 90 kB 6.0 MB/s 


In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
!cp /content/drive/MyDrive/dl_project/counterfactual_fairness_emotional_recognition-regularization.zip /content/
!unzip counterfactual_fairness_emotional_recognition-regularization.zip

Archive:  counterfactual_fairness_emotional_recognition-regularization.zip
bdbddcaf5be91b1547a8370c5c1c8af6c0f62085
   creating: counterfactual_fairness_emotional_recognition-regularization/
  inflating: counterfactual_fairness_emotional_recognition-regularization/.gitignore  
   creating: counterfactual_fairness_emotional_recognition-regularization/.vscode/
  inflating: counterfactual_fairness_emotional_recognition-regularization/.vscode/launch.json  
  inflating: counterfactual_fairness_emotional_recognition-regularization/.vscode/settings.json  
  inflating: counterfactual_fairness_emotional_recognition-regularization/README.md  
   creating: counterfactual_fairness_emotional_recognition-regularization/archive/
   creating: counterfactual_fairness_emotional_recognition-regularization/archive/baseline_ACRNN/
  inflating: counterfactual_fairness_emotional_recognition-regularization/archive/baseline_ACRNN/3-D.pdf  
  inflating: counterfactual_fairness_emotional_recognition-regularizati

In [17]:
!cp /content/drive/MyDrive/11785_Project/IEMOCAP_pkls.tar.gz /content/counterfactual_fairness_emotional_recognition-regularization/data

% cd /content/counterfactual_fairness_emotional_recognition-regularization/data
!tar -xvf IEMOCAP_pkls.tar.gz

/content/counterfactual_fairness_emotional_recognition-regularization/data
IEMOCAP_train.pkl
IEMOCAP_train_converted.pkl
IEMOCAP_eval.pkl
IEMOCAP_valid_data.npy
IEMOCAP_valid_gender.npy
IEMOCAP_valid_label.npy
IEMOCAP_test_data.npy
IEMOCAP_test_gender.npy
IEMOCAP_test_label.npy


# Train 10-20 models

In [1]:
# change the epoch num in train.py if necessary

% cd /content/counterfactual_fairness_emotional_recognition-regularization

for i in range(10):
    !python /content/counterfactual_fairness_emotional_recognition-regularization/train.py
    !cp -r -n /content/counterfactual_fairness_emotional_recognition-regularization/checkpoint /content/drive/MyDrive/dl_project/experiment_checkpoints
    ! cp -r -n /content/counterfactual_fairness_emotional_recognition-regularization/log /content/drive/MyDrive/dl_project/training_logs

Streaming output truncated to the last 5000 lines.
 [  0  14  16 184]]
Best Valid Confusion Matrix:["ang","sad","hap","neu"]
[[ 20   3   4   0]
 [  4  85  10   8]
 [ 23  12  22  23]
 [ 25 107  26  56]]
Learning Rate: 0.001
*****************************************************************
  0% 0/10 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:490: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1320: UserWarning: dropout2d: Received a 2-D input to dropout2d, which is deprecated and will result in an error in a future release. To retain the behavior and silenc

## Get test result

In [2]:
% cd /content/counterfactual_fairness_emotional_recognition-regularization

import pickle
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from datasets import IEMOCAPEval
import os
from train import test

/content/counterfactual_fairness_emotional_recognition-regularization


In [22]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score as recall
from sklearn.metrics import confusion_matrix as confusion
from datasets import IEMOCAPTrain, IEMOCAPEval
from utils.training_tracker import TrainingTracker
from utils.fairness_eval import FairnessEvaluation


In [4]:
model_dir = "/content/drive/MyDrive/dl_project/experiment_checkpoints/ensembled_models"
saved_models = os.listdir(model_dir)
saved_models = [os.path.join(model_dir, i) for i in saved_models]

In [6]:
# ! pwd

/content/counterfactual_fairness_emotional_recognition-regularization


In [11]:
test_dataset = IEMOCAPEval(partition='test')
test_loader = DataLoader(test_dataset, batch_size=128, shuffle=False, num_workers=1, pin_memory=True)
criterion = nn.CrossEntropyLoss()

# (test_sample_size, categories, models)
y_pred_enmodel = np.zeros(shape=(428, 4, len(saved_models)),dtype=np.float32)

In [13]:
# test return y_pred_test

for i in range(len(saved_models)):
    print("Testing model"+str(i))
    CHECKPOINT_MODEL_DIR = saved_models[i]
    model = torch.load(CHECKPOINT_MODEL_DIR).cuda()
    y_pred = test(model, test_loader, test_dataset, criterion)
    y_pred_enmodel[:,:,i] = y_pred

Testing model0


/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1320: UserWarning: dropout2d: Received a 2-D input to dropout2d, which is deprecated and will result in an error in a future release. To retain the behavior and silence this warning, please use dropout instead. Note that dropout2d exists to provide channel-wise dropout on inputs with 2 spatial dimensions, a channel dimension, and an optional batch dimension (i.e. 3D or 4D inputs).
  warnings.warn(warn_msg)


*****************************************************************
Evaluation on Test Set:
Test cost: 1.25
Test accuracy: 0.472
Test UAR: 0.532
Test Confusion Matrix:["ang","sad","hap","neu"]
[[22  1  3  3]
 [14 68  8 20]
 [18  5 25 23]
 [43 52 36 87]]
Fairness Scores (in terms of equal opportunities):
["ang","sad","hap","neu"]
[0.93333333 0.66576819 0.86666667 0.75497788]
*****************************************************************
Testing model1


/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1320: UserWarning: dropout2d: Received a 2-D input to dropout2d, which is deprecated and will result in an error in a future release. To retain the behavior and silence this warning, please use dropout instead. Note that dropout2d exists to provide channel-wise dropout on inputs with 2 spatial dimensions, a channel dimension, and an optional batch dimension (i.e. 3D or 4D inputs).
  warnings.warn(warn_msg)


*****************************************************************
Evaluation on Test Set:
Test cost: 1.23
Test accuracy: 0.509
Test UAR: 0.5294
Test Confusion Matrix:["ang","sad","hap","neu"]
[[ 26   1   0   2]
 [ 17  65   5  23]
 [ 26   3   5  37]
 [ 53  35   8 122]]
Fairness Scores (in terms of equal opportunities):
["ang","sad","hap","neu"]
[0.91836735 0.76415094 0.         0.66745606]
*****************************************************************
Testing model2


/content/counterfactual_fairness_emotional_recognition-regularization/utils/fairness_eval.py:39: RuntimeWarning: divide by zero encountered in double_scalars
  self.equal_opportunities = np.array([np.min((m[i, i] / f[i, i], f[i, i] / m[i, i])) for i in range(len(m))])
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1320: UserWarning: dropout2d: Received a 2-D input to dropout2d, which is deprecated and will result in an error in a future release. To retain the behavior and silence this warning, please use dropout instead. Note that dropout2d exists to provide channel-wise dropout on inputs with 2 spatial dimensions, a channel dimension, and an optional batch dimension (i.e. 3D or 4D inputs).
  warnings.warn(warn_msg)


*****************************************************************
Evaluation on Test Set:
Test cost: 1.31
Test accuracy: 0.416
Test UAR: 0.5337
Test Confusion Matrix:["ang","sad","hap","neu"]
[[27  0  1  1]
 [19 65  9 17]
 [24  7 23 17]
 [38 55 62 63]]
Fairness Scores (in terms of equal opportunities):
["ang","sad","hap","neu"]
[0.85714286 0.62954441 0.36437247 0.97835498]
*****************************************************************
Testing model3


/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1320: UserWarning: dropout2d: Received a 2-D input to dropout2d, which is deprecated and will result in an error in a future release. To retain the behavior and silence this warning, please use dropout instead. Note that dropout2d exists to provide channel-wise dropout on inputs with 2 spatial dimensions, a channel dimension, and an optional batch dimension (i.e. 3D or 4D inputs).
  warnings.warn(warn_msg)


*****************************************************************
Evaluation on Test Set:
Test cost: 1.35
Test accuracy: 0.369
Test UAR: 0.5198
Test Confusion Matrix:["ang","sad","hap","neu"]
[[26  1  2  0]
 [16 67 20  7]
 [23  8 29 11]
 [45 77 60 36]]
Fairness Scores (in terms of equal opportunities):
["ang","sad","hap","neu"]
[0.91836735 0.60026327 0.65934066 0.66371681]
*****************************************************************
Testing model4


/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1320: UserWarning: dropout2d: Received a 2-D input to dropout2d, which is deprecated and will result in an error in a future release. To retain the behavior and silence this warning, please use dropout instead. Note that dropout2d exists to provide channel-wise dropout on inputs with 2 spatial dimensions, a channel dimension, and an optional batch dimension (i.e. 3D or 4D inputs).
  warnings.warn(warn_msg)


*****************************************************************
Evaluation on Test Set:
Test cost: 1.28
Test accuracy: 0.404
Test UAR: 0.5197
Test Confusion Matrix:["ang","sad","hap","neu"]
[[24  0  4  1]
 [13 48 23 26]
 [23  2 37  9]
 [42 23 89 64]]
Fairness Scores (in terms of equal opportunities):
["ang","sad","hap","neu"]
[0.76530612 0.98943396 0.94920635 0.92920354]
*****************************************************************
Testing model5


/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1320: UserWarning: dropout2d: Received a 2-D input to dropout2d, which is deprecated and will result in an error in a future release. To retain the behavior and silence this warning, please use dropout instead. Note that dropout2d exists to provide channel-wise dropout on inputs with 2 spatial dimensions, a channel dimension, and an optional batch dimension (i.e. 3D or 4D inputs).
  warnings.warn(warn_msg)


*****************************************************************
Evaluation on Test Set:
Test cost: 1.27
Test accuracy: 0.465
Test UAR: 0.5238
Test Confusion Matrix:["ang","sad","hap","neu"]
[[ 27   1   1   0]
 [ 22  58   8  22]
 [ 30   3  12  26]
 [ 46  33  37 102]]
Fairness Scores (in terms of equal opportunities):
["ang","sad","hap","neu"]
[0.85714286 0.70673854 0.57692308 0.89346494]
*****************************************************************
Testing model6


/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1320: UserWarning: dropout2d: Received a 2-D input to dropout2d, which is deprecated and will result in an error in a future release. To retain the behavior and silence this warning, please use dropout instead. Note that dropout2d exists to provide channel-wise dropout on inputs with 2 spatial dimensions, a channel dimension, and an optional batch dimension (i.e. 3D or 4D inputs).
  warnings.warn(warn_msg)


*****************************************************************
Evaluation on Test Set:
Test cost: 1.25
Test accuracy: 0.495
Test UAR: 0.5266
Test Confusion Matrix:["ang","sad","hap","neu"]
[[ 24   0   2   3]
 [ 11  44  21  34]
 [ 20   1  23  27]
 [ 34  16  47 121]]
Fairness Scores (in terms of equal opportunities):
["ang","sad","hap","neu"]
[0.76530612 0.98195242 0.48076923 0.97645118]
*****************************************************************
Testing model7


/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1320: UserWarning: dropout2d: Received a 2-D input to dropout2d, which is deprecated and will result in an error in a future release. To retain the behavior and silence this warning, please use dropout instead. Note that dropout2d exists to provide channel-wise dropout on inputs with 2 spatial dimensions, a channel dimension, and an optional batch dimension (i.e. 3D or 4D inputs).
  warnings.warn(warn_msg)


*****************************************************************
Evaluation on Test Set:
Test cost: 1.28
Test accuracy: 0.446
Test UAR: 0.5375
Test Confusion Matrix:["ang","sad","hap","neu"]
[[26  1  2  0]
 [16 66 18 10]
 [24  5 21 21]
 [43 51 46 78]]
Fairness Scores (in terms of equal opportunities):
["ang","sad","hap","neu"]
[0.91836735 0.65577543 0.86538462 0.75632846]
*****************************************************************
Testing model8


/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1320: UserWarning: dropout2d: Received a 2-D input to dropout2d, which is deprecated and will result in an error in a future release. To retain the behavior and silence this warning, please use dropout instead. Note that dropout2d exists to provide channel-wise dropout on inputs with 2 spatial dimensions, a channel dimension, and an optional batch dimension (i.e. 3D or 4D inputs).
  warnings.warn(warn_msg)


*****************************************************************
Evaluation on Test Set:
Test cost: 1.28
Test accuracy: 0.444
Test UAR: 0.5136
Test Confusion Matrix:["ang","sad","hap","neu"]
[[26  1  1  1]
 [18 69  7 16]
 [22  8 10 31]
 [48 55 30 85]]
Fairness Scores (in terms of equal opportunities):
["ang","sad","hap","neu"]
[0.78571429 0.57358491 0.86666667 0.91242236]
*****************************************************************
Testing model9


/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1320: UserWarning: dropout2d: Received a 2-D input to dropout2d, which is deprecated and will result in an error in a future release. To retain the behavior and silence this warning, please use dropout instead. Note that dropout2d exists to provide channel-wise dropout on inputs with 2 spatial dimensions, a channel dimension, and an optional batch dimension (i.e. 3D or 4D inputs).
  warnings.warn(warn_msg)


*****************************************************************
Evaluation on Test Set:
Test cost: 1.26
Test accuracy: 0.474
Test UAR: 0.5284
Test Confusion Matrix:["ang","sad","hap","neu"]
[[25  2  1  1]
 [13 65 16 16]
 [23  5 15 28]
 [40 50 30 98]]
Fairness Scores (in terms of equal opportunities):
["ang","sad","hap","neu"]
[0.84183673 0.76415094 0.86538462 0.96792035]
*****************************************************************
Testing model10


/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1320: UserWarning: dropout2d: Received a 2-D input to dropout2d, which is deprecated and will result in an error in a future release. To retain the behavior and silence this warning, please use dropout instead. Note that dropout2d exists to provide channel-wise dropout on inputs with 2 spatial dimensions, a channel dimension, and an optional batch dimension (i.e. 3D or 4D inputs).
  warnings.warn(warn_msg)


*****************************************************************
Evaluation on Test Set:
Test cost: 1.34
Test accuracy: 0.383
Test UAR: 0.5373
Test Confusion Matrix:["ang","sad","hap","neu"]
[[25  1  2  1]
 [15 62 21 12]
 [17  6 39  9]
 [39 66 75 38]]
Fairness Scores (in terms of equal opportunities):
["ang","sad","hap","neu"]
[0.84183673 0.67924528 0.86538462 0.87120181]
*****************************************************************
Testing model11


/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1320: UserWarning: dropout2d: Received a 2-D input to dropout2d, which is deprecated and will result in an error in a future release. To retain the behavior and silence this warning, please use dropout instead. Note that dropout2d exists to provide channel-wise dropout on inputs with 2 spatial dimensions, a channel dimension, and an optional batch dimension (i.e. 3D or 4D inputs).
  warnings.warn(warn_msg)


*****************************************************************
Evaluation on Test Set:
Test cost: 1.31
Test accuracy: 0.418
Test UAR: 0.5274
Test Confusion Matrix:["ang","sad","hap","neu"]
[[24  1  3  1]
 [15 72 17  6]
 [14 10 26 21]
 [37 74 50 57]]
Fairness Scores (in terms of equal opportunities):
["ang","sad","hap","neu"]
[0.90659341 0.60787531 0.92444444 0.62857887]
*****************************************************************
Testing model12


/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1320: UserWarning: dropout2d: Received a 2-D input to dropout2d, which is deprecated and will result in an error in a future release. To retain the behavior and silence this warning, please use dropout instead. Note that dropout2d exists to provide channel-wise dropout on inputs with 2 spatial dimensions, a channel dimension, and an optional batch dimension (i.e. 3D or 4D inputs).
  warnings.warn(warn_msg)


*****************************************************************
Evaluation on Test Set:
Test cost: 1.29
Test accuracy: 0.442
Test UAR: 0.5214
Test Confusion Matrix:["ang","sad","hap","neu"]
[[26  1  1  1]
 [21 60  9 20]
 [22  6 18 25]
 [45 55 33 85]]
Fairness Scores (in terms of equal opportunities):
["ang","sad","hap","neu"]
[0.91836735 0.66853646 0.66568047 0.86584875]
*****************************************************************


In [15]:
category_pred = np.argmax(y_pred_enmodel, 1)

In [19]:
enmodel_vote = np.zeros(shape=428)
for s in range(category_pred.shape[0]):
    vote = np.bincount(category_pred[s,:]).argmax()
    enmodel_vote[s] = vote

In [23]:
# compute performance evaluation scores
test_accuracy = accuracy_score(test_dataset.label, enmodel_vote)
test_acc_uw = recall(test_dataset.label, enmodel_vote, average='macro')
test_conf = confusion(test_dataset.label, enmodel_vote)

# compute fairness evaluation scores
fairness_eval = FairnessEvaluation(test_dataset.gender, test_dataset.label, enmodel_vote)

# print results
print("*****************************************************************")
print(f"Evaluation on Test Set:")
print("Test accuracy: %2.3g" %test_accuracy)
print("Test UAR: %3.4g" %test_acc_uw)
print('Test Confusion Matrix:["ang","sad","hap","neu"]')
print(test_conf)
print('Fairness Scores (in terms of equal opportunities):')
fairness_eval.print_equal_opportunities()
print("*****************************************************************")


*****************************************************************
Evaluation on Test Set:
Test accuracy: 0.458
Test UAR: 0.5472
Test Confusion Matrix:["ang","sad","hap","neu"]
[[27  1  1  0]
 [18 65 13 14]
 [24  5 20 22]
 [45 50 39 84]]
Fairness Scores (in terms of equal opportunities):
["ang","sad","hap","neu"]
[0.85714286 0.62954441 0.74175824 0.97835498]
*****************************************************************
